version: '3.4'

services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    environment:
      POSTGRES_DATABASE: 'pergamon'
      POSTGRES_USER: 'pergamon'
      POSTGRES_PASSWORD: 'pergamon'
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always

  api:
    build: ./api
    ports:
      - 80:8888
    command: bash ./api/wait-for-it.sh db:5432
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/pergamon?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=pergamon
      - SPRING_DATASOURCE_PASSWORD=pergamon
      - SERVER_PORT=8888
    depends_on:
      - db


